### PR TITLE
fix: Use correct value path in object inspector (#2237)

### PR DESCRIPTION
**Pull request by rossketron**
## Description
Fixes known issue #2237.

If a property name includes a `.` such as in `{ 'property.name': 123 }`, the value is now accessed using bracket notation instead of `get()` in order to treat the name as a string literal and avoid attempting to access a nested value.

If a property name does not include a `.`, there is no change in functionality.

A test was added to ensure the correct value is accessed given this scenario.

### CODE REVIEW

**Comment by rwwagner90** [comment]
@rossketron thanks for the PR! Forgive my ignorance, but will this still work correctly for nested properties as well?

**Comment by patricklx** [comment]
I think it should be fine as it only iterates over the object keys. So there will be no nested access.

**Comment by rossketron** [comment]
@rwwagner90 @patricklx - Thanks for the feedback! 

I'm happy to add more robust testing for this as well if it would be helpful.

**Comment by patricklx** [comment]
What about digging into the property with the dot? Does it work? Look at function digIntoObject

**Review by rwwagner90 — APPROVED** [review]

**Pull request merged**
