### PR TITLE
Add ember-cli-sass to build CSS file

### LINKED ISSUE #648: 3 errors in tests re: view tree
screen shot 2017-04-07 at 11 18 47 am

### PR DESCRIPTION
**Pull request by cyril-sf**
It seems like since moving to a table based `x-list`, the scroll
container for vertical collection didn't have the proper height to allow
rendering all the components.

Fixes #648

### CODE REVIEW

**Comment by cyril-sf** [comment]
I don't understand how this worked before.

**Comment by cyril-sf** [comment]
This may not be the right fix. It looks like there's a broader CSS issue

I'm running my local version of the inspector and it doesn't look good

screen shot 2017-04-19 at 11 58 27 am

**Comment by cyril-sf** [comment]
Still don't understand how this happened in the first place, but this feels like the right solution 😄

**Comment by cyril-sf** [comment]
@mixonic ready for review!

**Comment by teddyzeenny** [comment]
Thanks @cyril-sf!

**Pull request merged**
