### PR TITLE
`run` is missing from a couple of build commands

### PR DESCRIPTION
**Pull request by bjoska**
First I want to thank everyone working on this for an amazing tool.

While setting up the project on my machine I noticed that `run` was missing from a couple of commands in the README.md.

Figured I would create a PR instead of just opening an issue, hope that is ok. 

Cheers,
Björn

### CODE REVIEW

**Comment by teddyzeenny** [comment]
Thanks! Can you also update [package.json](https://github.com/emberjs/ember-inspector/blob/cfc282e78d0fc8c735d37d9fd31ce3b204503228/package.json#L15-L17)?

**Comment by bjoska** [comment]
Of course. 

Sorry about that!

**Comment by bjoska** [comment]
That should do it! @teddyzeenny 

:smile:

**Comment by teddyzeenny** [comment]
Looks great! Can you squash the commits?

**Comment by bjoska** [comment]
Done!

**Pull request merged**
