### PR TITLE
Current route only persists now after changing tabs if checked

### PR DESCRIPTION
**Pull request by chrism**
Hi,

This adds the queryParam as requested here
https://github.com/emberjs/ember-inspector/issues/567

I haven't written a test, but have tried it locally and it appears to work.

### CODE REVIEW

**Comment by teddyzeenny** [comment]
Hey! Thanks for working on this 😄 

I think this is missing `hideRoutes: alias('options.hideRoutes')`? Are you sure it's working?

The commit message says "Current route only persists now after changing tabs if checked", however we need it to persist across refreshes.

- Go to "Routes"
- Check "Current Route Only"
- Refresh the page
- "Current Route Only" should be checked

**Comment by chrism** [comment]
Hey!

Sorry you are totally right — I didn't check between refreshes, but have added the extra alias and now it does.

Hopefully now this is good to merge - unless you'd prefer me to try to squash the two commits?

Thanks

**Comment by teddyzeenny** [comment]
Looks good - yes squash the commits if you don't mind.

**Comment by chrism** [comment]
👍

**Pull request merged**
