### PR TITLE
Side docked inspector ergonimics

### PR DESCRIPTION
**Pull request by betocantu93**
## Issue and Steps to Reproduce
There are a few css improvements that can bump dev experience while using the inspector docked at right/left

1. z-index for records lists / tables
2. the sidebar toggling button hides pretty easily.

## Your environment

Chrome, Ember version 3.15, inspector >= 3.13

### 1. z-index for records lists / tables
Screen Shot 2019-12-26 at 12 07 49 AM

### 2. the sidebar toggling button hides pretty easily
Screen Shot 2019-12-26 at 12 11 54 AM

Not sure if this would be the best way to solve it, but since we ideally want the toggler "show/hide" always visible, I placed the button inside the object-inspector panel too, using absolute positioning. 

Tests are missing, but first I wanted to get feedback, thanks

### CODE REVIEW

**Comment by rwwagner90** [comment]
@betocantu93 we are working on some of the overflow issues as part of this PR https://github.com/emberjs/ember-inspector/pull/1112

Things have somewhat stalled with the holidays, but I will pick it back up soon.

**Comment by betocantu93** [comment]
@rwwagner90 aight, let me know if anything, happy holidays

**Comment by rwwagner90** [comment]
@betocantu93 is everything sufficiently working for you now with overflows?

**Comment by betocantu93** [comment]
Hey @rwwagner90 , yes I believe all of them are now solved, thanks!

**Pull request closed without merging**
