### PR TITLE
remove title

### PR DESCRIPTION
**Pull request by patricklx**
follow up of #2426 
Forgot to revert this...

### CODE REVIEW

**Review by RobbieTheWagner — APPROVED** [review]
Changes look fine, but we have some test failures somehow.

**Comment by patricklx** [comment]
strange... it's not the tooltip issue, but the highlighter offset is somehow changed now... 
works okay in browser test, but not in headless...

**Comment by patricklx** [comment]
i guess showing the tooltip causes the scrollbars to appear, which then offsets the component

**Review by RobbieTheWagner — APPROVED** [review]

**Comment by patricklx** [comment]
@RobbieTheWagner can you remove the label? Or change it? It's not necessary for this to appear in the changelog :)

**Pull request merged**
