### PR TITLE
search-field  Component Bug Fix and Acceptance Tests

### PR DESCRIPTION
**Pull request by nummi**
Changed clear button from DOM removal to 0 opacity because this causes problems in testing. When clicking on a button, it gets focus. But if you remove a focused element from the DOM, the entire window loses focus.

### CODE REVIEW

**Comment by rwwagner90** [comment]
@nummi did this not cause issues before or were we just not testing before? Wouldn't it be shown in tests as well, when the if condition is true?

**Comment by rwwagner90** [comment]
Oh, yeah, should it be `if searchValue`? I think that was the name, right?

**Comment by nummi** [comment]
> Oh, yeah, should it be if searchValue? I think that was the name, right?

Correct. The component is called like: `{{search-field value=searchValue}}`

**Comment by rwwagner90** [comment]
So can we put in the appropriate `if` statement? Trying to determine why we want to style opacity, rather than using an `if`.

**Comment by rwwagner90** [comment]
@teddyzeenny any thoughts on this? If you are okay with the opacity approach, we can keep it as is. I'd like to figure out how to use an `if`, as I think that is more clear to people jumping into the code later, but getting this in and iterating later is also fine with me.

**Comment by teddyzeenny** [comment]
@rwwagner90 @nummi I'll take a look during the weekend. Ideally we can fix this at the source of the error on [`x-app`](https://github.com/emberjs/ember-inspector/blob/317f4d1b1297053aa384570761fa84fc122a3ee1/app/components/x-app.js#L27-L37) by maybe scheduling or debouncing the `active` toggle using the run loop? If it works it would be better than removing the `if` as a workaround IMO.

**Comment by rwwagner90** [comment]
@nummi can you explore that option?

**Comment by rwwagner90** [comment]
That could work. @teddyzeenny would that work for you?

**Comment by teddyzeenny** [comment]
That works! :shipit:

**Comment by rwwagner90** [comment]
Thanks @nummi!

**Pull request merged**
