### PR TITLE
Filter out object properties by property name filter/search

### LINKED ISSUE #1171: Filter out object properties by property name filter/search
It would be useful to filter properties on an object in the object inspector sidebar. 

Something like this:

CleanShot 2020-04-06 at 11 41 56@2x

Similar to how you can filter in other places in devtools. Ex:

CleanShot 2020-04-06 at 11 45 21

### PR DESCRIPTION
**Pull request by ansmonjol**
## Description

This MR aims to filter object properties by name.

If the user start typing a custom search, he's redirected to the "All" filter section and a filter is applied on the object properties displayed (flat).

## Result
ezgif com-video-to-gif

Closes #1171

### CODE REVIEW

**Comment by nummi** [comment]
Hey @ansmonjol,

I can't seem to open a pull request against your Github repo. I was going to suggest a few changes:

1. More consistent styling with other toolbar search inputs
2. `data-test` selectors
3. Empty state

Screen Shot 2020-04-11 at 5 14 33 PM

Screen Shot 2020-04-11 at 5 14 45 PM

**Comment by ansmonjol** [comment]
Hey guys !

Thank you so much for your feedbacks.

You can find the changes regarding your suggestions about:
- UI consistency: https://github.com/emberjs/ember-inspector/pull/1172/commits/b070d966234cb38fac98d1f358efc44440c53b4c
- `data-test` use (I'll have a look at other used selector and try to replace them all with data-test) https://github.com/emberjs/ember-inspector/pull/1172/commits/29c7e02db258d69a393e7d2adc7a9123c2d3b566
- Add empty state https://github.com/emberjs/ember-inspector/pull/1172/commits/fdb70f955727e6862a6bdc046a5bc00a917bc2df

I also found a solution for the failing tests ! https://github.com/emberjs/ember-inspector/pull/1172/commits/e7a87db67b04a99e3a11f0ef5401db09f46e5283

I used the same method as in `toolbar-search-field` in order to focus the input on clear press.

So now I have another fail in the CI hahaha. https://codeclimate.com/github/emberjs/ember-inspector/pull/1172
I would not opt to refactor this but do you think this method should be placed into a helper or something shared between both components ? 

Also, I added you to the contributor list of my repo. You should now be able to create a MR against this repo.
Let me know if that works.

**Comment by rwwagner90** [comment]
@ansmonjol it looks like the build is green now, so I will review this soon!

**Comment by rwwagner90** [comment]
I tested this out locally, and all seems to work well.

**Pull request merged**
