### PR TITLE
Fix Inspector tab display in Firefox Developer Edition

### PR DESCRIPTION
**Pull request by pbishop16**
Description:
---
- Addresses #802 
- Error due to the property `options_page` in manifest.json

image

### CODE REVIEW

**Comment by nummi** [comment]
Looks good to me.

**Comment by nummi** [comment]
@pbishop16, where did you go in Firefox to see that error message?

**Comment by pbishop16** [comment]
@nummi I went to `Debug Add-ons` listed under the menu on the Add-ons Manager page. On the `Debug Add-ons` page, any errors will be listed on the add-on panels.

**Comment by yohanmishkin** [comment]
Thanks so much for the work on this. I believe I may still be having the same. Let me know if there's anything I can do to help diagnose. Thanks!

**Comment by rwwagner90** [comment]
@yohanmishkin we have not released a new version since this was merged.

**Pull request merged**
