### PR TITLE
Release 4.3.5

### PR DESCRIPTION
**Pull request by steventsao**
## Description
Push tag using `release-it`

See [original PR](https://github.com/emberjs/ember-inspector/pull/1520) for context

### CODE REVIEW

**Comment by steventsao** [comment]
@rwwagner90 Thanks

**Review by rwwagner90 — APPROVED** [review]

**Comment by steventsao** [comment]
@rwwagner90 Can you tag this commit?

**Comment by rwwagner90** [comment]
@chancancode how do we handle this? Typically I would push release-it commits straight to master, but we disallow that for this repo. I can manually tag, but seems like we should be able to release with one command.

**Comment by chancancode** [comment]
looks like you manually tagged the commit right? 👍 

I don't have a strong opinion, I'm pretty sure the PR-only workflow predated my involvement (and also predated release-it). I would be fine with admins pushing directly to master for releases, but @rwjblue can chime in on best practice here.

**Pull request merged**
