### PR TITLE
filter out null/undefined nodes

### LINKED ISSUE #506: TypeError: Cannot read property 'getState' of undefined
I updated my Ember app from 1.13.11 to 2.3.0-beta.3. If I open the Ember inspector (1.9.4) and navigate around, the following error is thrown:

```
TypeError: Cannot read property 'getState' of undefined
    at _nodeIsView (<anonymous>:4196:21)
    at _shouldShowNode (<anonymous>:4164:17)
    at <anonymous>:4123:20
    at Array.forEach (native)
    at _appendNodeChildren (<anonymous>:4122:18)
    at <anonymous>:4128:18
    at Array.forEach (native)
    at _appendNodeChildren (<anonymous>:4122:18)
    at <anonymous>:4126:18
    at Array.forEach (native)
```

Unfortunately I can't isolate the error any further.

### PR DESCRIPTION
**Pull request by sly7-7**
fixes #506
closes #504

### CODE REVIEW

**Comment by Patsy-issa** [comment]
Tests are failing due to https://github.com/emberjs/ember.js/pull/12793

**Comment by IgorKvasn** [comment]
I don't want to sound rude, but can you pls fix this PR? 
Due to #506 I cannot use ember-inspector at all
thx

**Comment by sly7-7** [comment]
@IgorKvasn I think the pr is not responsible for the broken build, but I don't know what should be done for it to pass.
cc/ @rwjblue @teddyzeenny

**Comment by rwjblue** [comment]
I think https://github.com/emberjs/ember-inspector/pull/512 should fix the build.

**Comment by rwjblue** [comment]
I restarted the build now that #512 is merged.

**Comment by sly7-7** [comment]
Thanks, I just tried to force-push, but without change it does not work

**Comment by rwjblue** [comment]
Looks like build passed.

**Pull request merged**
