### PR TITLE
WIP: Context menu item for "Inspect Ember Component"

### PR DESCRIPTION
**Pull request by thorsteinsson**
image

This adds "Inspect Ember Component" context menu item to all pages when Ember has been detected. It adds the object id to the query string which keeps the component selected between page refreshes.

Things to improve:
- [ ] Add tests.
- [ ] Scroll to the selected component in the inspector.
- [ ] Show a message when the ember inspector is not visible (tell the user to open the inspector, not possible with code).
- [ ] Show a message when a component is not found.

### CODE REVIEW

**Comment by thorsteinsson** [comment]
@Bestra and I paired on this at Emberconf contributors workshop for #689.

**Comment by rwwagner90** [comment]
@thorsteinsson @Bestra @nummi does anyone have cycles to help get this over the finish line?

**Comment by Bestra** [comment]
@rwwagner90 I think I'll have at least a half day to work on it this Friday.  @thorsteinsson would you be okay with me adding some commits to your branch if I get the time?

**Comment by thorsteinsson** [comment]
Of course, go ahead. I've been so busy at work, hoping to get some time tomorrow.

**Comment by rwwagner90** [comment]
Is anyone actively working on this?

**Comment by Bestra** [comment]
@thorsteinsson I'm closing this one in favor of #843, which is essentially this PR with two extra commits from me.  Good work!

**Pull request closed without merging**
