### PR TITLE
limit max width of tooltips

### PR DESCRIPTION
**Pull request by patricklx**
## Description
limit width of tooltips and clips too long content.
On hover it will show the full string as tooltip, via title attribute

### CODE REVIEW

**Comment by RobbieTheWagner** [comment]
@patricklx can you please give me an example of when this is needed and possibly some before/after screenshots?

**Comment by patricklx** [comment]
Screenshot 2023-07-10 141141
Screenshot 2023-07-10 141207

**Comment by RobbieTheWagner** [comment]
I'm still not sure on whether we want to limit this or not.

**Comment by patricklx** [comment]
That can also be done. Is that preferred @RobbieTheWagner ?

**Comment by patricklx** [comment]
would like like this:

image

**Comment by NullVoxPopuli** [comment]
oooo I like that

**Review by NullVoxPopuli — APPROVED** [review]

**Comment by RobbieTheWagner** [comment]
Wrapping is definitely preferred here. Are the wrapping changes in?

**Review by RobbieTheWagner — APPROVED** [review]

**Pull request merged**
