### PR TITLE
Adding CSP to app to see if it fixes issue

### LINKED ISSUE #819: Can't select the Ember inspector tab in Firefox
I am currently on firefox version 61.0b11 and I can't seem to select the Ember inspector tab. I have tried this with multiple pages that use Ember, but it seems to be a firefox issue. I don't get any error in the console when trying to go to the Ember inspector tab. I currently have version 3.1.3 of the inspector installed.

### PR DESCRIPTION
**Pull request by jrock2004**
This is an attempt to fix #819

### CODE REVIEW

**Comment by rwwagner90** [comment]
@jrock2004 did this help? How can we test this?

cc @pbishop16

**Comment by jrock2004** [comment]
I need to see why that test is failing. Again since when running locally this all works, I am not sure if this will fix it. But since its complaining about CSP I am thinking by adding the default it should work

**Comment by jrock2004** [comment]
@rwwagner90 you can take my branch and compile it locally and try it yourself. If your asking if there are test cases we can write, 🤔

**Comment by rwwagner90** [comment]
@jrock2004 I don't mean writing tests, I mean running in FF and seeing if it works. The locally running version has always worked, and we only hit the error from the store version, so trying to figure out how to see if this helps.

Any ideas @teddyzeenny @pbishop16?

**Comment by pbishop16** [comment]
@rwwagner90 Agreed. Based on what I have experienced so far, to test we would have to upload the version to the add-on store.

**Comment by rwwagner90** [comment]
It was a bug in FF, so closing this.

**Pull request closed without merging**
