### PR TITLE
Send to Console Buttons to SVG

### PR DESCRIPTION
**Pull request by nummi**
Move to SVG because PNG isn't scalable and SVG supports theming better. ☀️

### CODE REVIEW

**Comment by rwwagner90** [comment]
@nummi is this still a WIP?

**Comment by nummi** [comment]
@rwwagner90, I believe there was some cleanup I wanted to do.

**Comment by rwwagner90** [comment]
Sure thing @nummi. Just let me know when it's ready for review!

**Comment by nummi** [comment]
themes

@rwwagner90 — I can't remember what else I wanted to change :-P

**Comment by rwwagner90** [comment]
Looks good to me @nummi! Feel free to push the big green button, if there is nothing else you want to tweak 😄

**Comment by rwwagner90** [comment]
Went ahead and merged, so we can make sure this gets in the next release. Thanks!

**Pull request merged**
