### PR TITLE
add script tag to the head instead

### LINKED ISSUE #2243: in-page-script.js inserted into Wordpress editor
**Describe the bug**
`<script src="chrome-extension://bmdblncegkenkacieihfhpjfppoconhi/scripts/in-page-script.js" type="text/javascript"></script>` is inserted into the Wordpress editor and saved to the database. 

**To Reproduce**
1. Edit a page/post in Wordpress with the old/classic editor enabled and the 'Visual' mode as default. (classic-editor plugin is enabled on the sites I tested)
2. Click on the 'text' mode for the editor and see that the script is inserted

I don't know if the new gutenberg editor also has this problem, but I guess that every editor that uses iframes is effected.

**Expected behavior**
ember-inspector should not insert the in-page-script in the editor

### PR DESCRIPTION
**Pull request by patricklx**
fixes #2243 
with this it wont be intercepted by the wordpress editor

### CODE REVIEW

**Comment by patricklx** [comment]
its already beeing removed

**Comment by rwwagner90** [comment]
@patricklx could this cause potential timing issues?

**Comment by patricklx** [comment]
I don't think there should be any timing issue. Or what do you mean. At least the loaded script waits for the page load to complete and then executes the code

**Comment by rwwagner90** [comment]
> I don't think there should be any timing issue. Or what do you mean. At least the loaded script waits for the page load to complete and then executes the code

I mean moving to executing in the head will make it run earlier. Could there be things that are not ready at that time? I would assume we were putting it in the body for a reason before?

**Comment by patricklx** [comment]
I just checked the history of the script tag, and indeed in older versions it was depending on jQuery to subscribe to page load. Now its not using any library. So it can be safely loaded in the head tag

**Review by rwwagner90 — APPROVED** [review]

**Pull request merged**
