### PR TITLE
Show inspector commit id in info tab

### PR DESCRIPTION
**Pull request by okket**
For the internal version that shows up on the info tab use the version string from ember-cli-app-version. The `const version` has to stay because a regex in Gruntfile.js is looking for it.

### CODE REVIEW

**Comment by okket** [comment]
Ok, I get it now, the `const version` string gets overwritten by the Gruntfile.js rule. I guess that is superfluous now. I'll remove it for this PR.

**Comment by teddyzeenny** [comment]
Nice, I like that. Though I feel like maybe we should only do that in non-production builds? I'm not sure we should show the commit id in the published version (like the Ember.js does).

**Comment by rwjblue** [comment]
@teddyzeenny - `ember-cli-app-version` is using `git-repo-version` ([here](https://github.com/embersherpa/ember-cli-app-version/blob/v0.3.5/index.js#L9-L13)) which checks if we are on a tag ([here](https://github.com/cibernox/git-repo-version/blob/master/index.js#L11-L14)) and returns it if we are.  

Ember itself uses `git-repo-version` (the underlying library) [here](https://github.com/emberjs/emberjs-build/blob/master/lib/utils/replace-version.js#L9).

@okket - Can you rebase?

**Comment by teddyzeenny** [comment]
@rwjblue nice!

**Comment by rwjblue** [comment]
@okket - Ping?

**Comment by locks** [comment]
Closing due to inactivity. @okket if you're still around and want this, I'd love to merge a fresh PR!

**Pull request closed without merging**
