### PR TITLE
Add undefined check for getDescriptorFor()

### PR DESCRIPTION
**Pull request by AbhinavVishak**
Fixes https://github.com/emberjs/ember-inspector/issues/999.

`getDescriptorFor()` returns undefined for certain properties ( like computed properties through _ember-redux_, for example), so wrap it with a logical OR to prevent the _dependentKeys accessor from throwing an exception.

### CODE REVIEW

**Comment by rwwagner90** [comment]
@pzuraq is this the best fix for this?

**Comment by pzuraq** [comment]
We should replace: https://github.com/emberjs/ember-inspector/blob/master/ember_debug/utils/type-check.js#L33

with:

```
let { descriptorForDecorator, descriptorForProperty } = Ember.__loader.require('@ember/-internals/metal');

return descriptorForProperty(object[key]) || descriptorForDecorator(object[key]);
```

**Comment by rwwagner90** [comment]
@AbhinavVishak do you mind updating the PR to do the changes @pzuraq suggested?

**Comment by AbhinavVishak** [comment]
Sure. Let me try that and see how it behaves.

**Comment by rwwagner90** [comment]
@AbhinavVishak did those changes work well for your use case?

**Comment by AbhinavVishak** [comment]
@rwwagner90, sorry I haven't got a chance to test them out yet. Shall I leave a comment when I do so ?
Also, shouldn't the conditionals be flipped ? `descriptorForProperty(object, key) || descriptorForDecorator(object[key]);`

Check for a normal decorator first, and if not available then check for a property ?

**Comment by AbhinavVishak** [comment]
seems to work as expected. shows the appropriate dependent key for a computed property too. 👍

**Comment by rwwagner90** [comment]
> Also, shouldn't the conditionals be flipped to to
> 
> `descriptorForDecorator(object[key]) || descriptorForProperty(object, key);` ?

@pzuraq does the ordering matter? Should we flip them or leave them as is?

**Pull request merged**
