### PR TITLE
Adding ability for communication between extensions

### PR DESCRIPTION
**Pull request by pete-the-pete**
#261 and #115 inspired me to create an addon that enables the ember inspector to work with a chrome extension.  I haven't published it yet since it depends on changes to ember-inspector, but wanted to see if it would be useful for anyone.

the addon is here: [pete_the_pete/ember-cli-inspector-bridge](https://github.com/pete-the-pete/ember-cli-inspector-bridge)

### CODE REVIEW

**Comment by jlsalvador** [comment]
I was developing a password manager that uses Ember, and this plugin can save me time debugging. What do you (ember-inspect devs) need to make this thing happen?

**Comment by rwwagner90** [comment]
@teddyzeenny do we still want this functionality?

**Comment by rwwagner90** [comment]
@thorsteinsson any insights into this? I'm not exactly sure what this gives us. I think you probably know more about Chrome extensions than I do 😃

**Comment by rwwagner90** [comment]
We will investigate supporting extensions as part of the standalone app.

**Pull request closed without merging**
