### PR TITLE
[WIP] Trying to fix beta and canary

### PR DESCRIPTION
**Pull request by rwwagner90**
Our builds are all failing now, due to ember-beta and ember-canary changes. I'm working to resolve some of the issues here, but if anyone knows of specific things I should be on the lookout for and definitely change, let me know!

cc @rwjblue @teddyzeenny

### CODE REVIEW

**Comment by rwjblue** [comment]
See https://github.com/emberjs/ember.js/pull/16478 for details. I believe that PR was closed and reopened as https://github.com/emberjs/ember.js/pull/16499#pullrequestreview-112383911 (which was just merged).

Can you double check if that was the only change required? I’ll get it cherry picked into beta before the next one gets cut...

**Comment by rwwagner90** [comment]
@rwjblue I tried latest canary and I see another issue:

```
not ok 14 Chrome 65.0 - Ember Debug - Object Inspector: Property grouping can be customized using _debugInfo
    ---
        actual: >
            null
        stack: >
            TypeError: Cannot add property __NAME_KEY__ember15238817701531233187778522__, object is not extensible
```

There are also a couple more failures, related to things like `this.get(...).on is not a function`, but I think maybe those are just things we need to update?

**Comment by rwjblue** [comment]
That failure is the thing reported in https://github.com/emberjs/ember.js/issues/16479, I'm working on a PR to fix it now...

**Comment by rwwagner90** [comment]
@rwjblue canary is passing now, so we should be green, or mostly green when a new beta release is cut. Thanks so much for everything you do! 😄

**Pull request merged**
