### PR TITLE
Remove Orange from Dark Theme

### PR DESCRIPTION
**Pull request by nummi**
Old:
screen shot 2018-12-11 at 8 19 18 pm

New:
screen shot 2018-12-11 at 8 19 28 pm

### CODE REVIEW

**Comment by rwwagner90** [comment]
@nummi I do agree this looks more pleasing, but what necessitated the change? Did we have bad contrast issues? We should make sure all our dark mode colors are good for color blind people probably.

**Comment by nummi** [comment]
Both the black on orange and white on blue pass WCAG AA for normal sized text. Part of the change is personal (I'm not a fan of the orange on dark grey), the other is more convention — all of the dark UIs I've seen don't simply invert their colors. In the future I do think some of the lines in the dark theme need to be increased in contrast (the border under the toolbar for example).

screen shot 2018-12-12 at 8 52 20 am
screen shot 2018-12-12 at 8 51 52 am
screen shot 2018-12-12 at 8 51 20 am
screen shot 2018-12-12 at 8 51 04 am

**Comment by pbishop16** [comment]
@rwwagner90 I agree with @nummi's assessment and addition insights regarding future contrast refinements.

**Comment by stefanpenner** [comment]
I like it!

**Comment by rwwagner90** [comment]
@nummi looks like we have some stylelint issues. We also have failing builds in beta now that we need to figure out.

**Comment by nummi** [comment]
Stylelint fixed.

**Comment by rwwagner90** [comment]
@locks @MelSumner @nummi does this meet accessibility standards to your liking? It looks good to me.

**Pull request merged**
