### PR TITLE
WIP Upgrade Ember v1.12 > v1.13 (CLI included)

### PR DESCRIPTION
**Pull request by raido**
It builds, some tests even pass and it actually boots and detects your app but that's about it.

### CODE REVIEW

**Comment by teddyzeenny** [comment]
Wow thanks for tackling that! What's the status of this? Do you need help / is this ready for review?

**Comment by raido** [comment]
Still working on it. There are some failing tests still which i need help with. 

Then all the views need to be converted to components. 

And generally it is quite broken, things that are not covered with tests. 

I'll ping you on Slack in few days.

**Comment by teddyzeenny** [comment]
I have an open branch too on my local machine where I rewrote some things to remove deprecations. I'll see if I can sync up with yours.

**Comment by teddyzeenny** [comment]
@raido I'm working on this. I had a lot of trouble merging your branch with mine because CONFLICTS!! I'm manually cherry picking things from your branch that have not been addressed in my branch and finalizing the upgrade. Will ping you when I'm done!! Thanks again!

**Comment by raido** [comment]
@teddyzeenny Great, let me know when you have conflict free branch. I can checkout new branch from it and help you finish.

**Comment by teddyzeenny** [comment]
Superseded by https://github.com/emberjs/ember-inspector/pull/563. @raido if you have some time do you mind taking a look at the new PR?

**Comment by raido** [comment]
@teddyzeenny Great work! I'll look at in couple of days, I am on vacation.

**Pull request closed without merging**
