### PR TITLE
Fix tracked detection

### PR DESCRIPTION
**Pull request by patricklx**
call getter directly
Ember.get auto tracks properties is seems, breaking the tracked detection.
So, it marks Getters as tracked, if the getter does not depend on any tracked property,

### CODE REVIEW

**Comment by rwwagner90** [comment]
@pzuraq does this seem logical to you? I don't know about the internals.

**Comment by rwwagner90** [comment]
@patricklx if this fixes a bug in tracked detection, would it be possible to add a test covering that bug, that would fail before and passes now?

**Comment by pzuraq** [comment]
`get` should never mark a getter as anything. It will install a mandatory getter/setter on plain properties, but it does nothing unusual to plain getters. Can you describe the failure you were seeing in a bit more detail?

**Comment by patricklx** [comment]
its not that `get` marks it, but it adds the property tag into the tracking tags.
But we try to detect a tracked by checking if `metal.track` returns the same which metal.tagForProperty returns.
Which happens when accessing getters through `get`.  https://github.com/emberjs/ember.js/blob/master/packages/%40ember/-internals/metal/lib/property_get.ts#L110

**Comment by pzuraq** [comment]
Ah, ok, makes sense. I think this is fine for now 👍

**Pull request merged**
