### PR TITLE
fix some pages not loading

### PR DESCRIPTION
**Pull request by patricklx**
e.g. render performance page did not load and possibly other issues
because chunks of webpack where not loaded since url was wrong

https://github.com/ef4/ember-auto-import/issues/540

### CODE REVIEW

**Comment by rwwagner90** [comment]
@patricklx can you please explain this some more? I do not understand when this is an issue. The render performance page works for me without this. Is this if apps are using embroider or something?

**Comment by patricklx** [comment]
@rwwagner90 sorry, I mean this is not working in the current main branch and can be seen with the nightly build on chrome: https://chrome.google.com/webstore/detail/ember-inspector-nightly/ibdbkmdgflhglikhjdbogjjflkialpfi
the problem also exists in the current release, when I inspect the ember-inspector requests I see that it fails to request the chunks. I guess it was just luck that it does not seem to break anything.

**Comment by patricklx** [comment]
image

**Comment by patricklx** [comment]
also, if you look at the generated index.html script src:
```html
<body class="ember-application theme--light">
    

    <script src="assets/vendor.js"></script>
<script src="/assets/chunk.131.94e9295903c351885e48.js"></script>
<script src="/assets/chunk.143.2f2438030067e3bf00af.js"></script>
    <script src="assets/ember-inspector.js"></script>
...
</body>
```

**Review by rwwagner90 — APPROVED** [review]

**Pull request merged**
