### PR TITLE
cleanup iframes & firefox skeleton

### PR DESCRIPTION
**Pull request by patricklx**
iframe is now done via windows messages
firefox skeleton is not used

### CODE REVIEW

**Comment by rwwagner90** [comment]
@patricklx are you sure firefox skeleton is not used? I know we still build for firefox.

**Comment by patricklx** [comment]
Yeah, but the build output for Firefox shows its just using the web extension skeleton. Nothing from Firefox inside

**Comment by patricklx** [comment]
@rwwagner90 anything special i need to do to load the extension in Firefox? I was unable to do it. With or without this change

**Comment by patricklx** [comment]
confirmed that this works in firefox

**Comment by rwwagner90** [comment]
@patricklx so Firefox just uses the Chrome extension build? I'm confused why we don't need any configs for Firefox.

**Comment by patricklx** [comment]
yeah, it uses the same as chrome. those are the WebExtension APIs and there are only some incompatibilities https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Chrome_incompatibilities

**Comment by rwwagner90** [comment]
@patricklx so if I approved and merge this PR, our builds will still create a firefox.zip and publish it to their store? Just making 100% sure here.

**Comment by patricklx** [comment]
yeah, i tried it locally

**Review by rwwagner90 — APPROVED** [review]

**Pull request merged**
