### PR TITLE
update vertical-collection & ember-table

### LINKED ISSUE #2200: ember inspector stops responding, error: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
**Describe the bug**
inspector stops responding to any interaction, error in inspector is 
Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
- While rendering:
  -top-level
    application
      app-detected
        component-tree
          scroll-container
            vertical-collection

**To Reproduce**
inconsistent, hard to reproduce consistently 

happens when children are being removed from the component tree.
This seems to happen when there are many renders.
I have a clock which updates a few times per second. When addition interaction is done it increases the likelihood

### PR DESCRIPTION
**Pull request by patricklx**
fixes #2200

### CODE REVIEW

**Comment by patricklx** [comment]
this always fails locally, but looks like its working in CI...

**Comment by patricklx** [comment]
i think its really just a problem on vertical collection. vertical collection is used directly for the component tree. other routes are indeed using ember-table and I saw that it has the same problem

**Comment by patricklx** [comment]
@rwwagner90 you might be right about updating ember-table. its still using the older version of vertical-collection and it looks like ember-inspector is picking that one...

**Comment by patricklx** [comment]
right, the test for the issue passed, but a bunch of other issues. ill look into them to update ember-table

**Review by rwwagner90 — APPROVED** [review]

**Comment by rwwagner90** [comment]
Thanks @patricklx!

**Pull request merged**
