### PR TITLE
Firefox WebExtension

### LINKED ISSUE #666: Convert Firefox add-on to use the Chrome WebExtension
Here's a tracking issue to pull in all the related pieces needed to make the current WebExtension work within Firefox.  Firefox 57 (coming in November) will be removing support for the add-on SDK and should have full support for all the WebExtension APIs used here.

- [x] `chrome.extension.onConnect` used [here](https://github.com/emberjs/ember-inspector/blob/master/skeletons/chrome/background-script.js#L75), needs to be updated to use [runtime.onConnect](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/runtime/onConnect)
- [x] `chrome.extension.onMessage` used [here](https://github.com/emberjs/ember-inspector/blob/master/skeletons/chrome/background-script.js#L109) needs to be updated to use [runtime.onMessage](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/runtime/onMessage)
- [x] `chrome.extension.sendMessage` used a lot in [content-script.js](https://github.com/emberjs/ember-inspector/blob/master/skeletons/chrome/content-script.js#L43) needs to be updated to use [runtime.sendMessage](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/runtime/sendMessage)

I'll look through the rest of the errors and keep updating this list as I go.

### PR DESCRIPTION
**Pull request by clarkbw**
This PR fixes #666 

There is still more work to do to migrate the build / packaging of Firefox over to the WebExtension, this PR is focused on updating the chrome WebExtension so that it works in Firefox.

### CODE REVIEW

**Comment by locks** [comment]
Hey :) Can you enumerate the missing work, in case someone else can/wants to contribute?

**Comment by clarkbw** [comment]
> Hey :) Can you enumerate the missing work, in case someone else can/wants to contribute?

Sure, its all detailed in #666.  I don't currently have a working ember inspector build for Chrome or Firefox so I got a bit stuck there.  If you can take this PR and get a working ember inspect you could do the testing required to move forward with any other issues that come up.

**Comment by teddyzeenny** [comment]
Hi @clarkbw. Sorry for the super late reply! Thanks a lot for working on this. This looks good! If you rebase this branch with current master you shouldn't have a problem running it on Chrome. All issues have been resolved.

It won't work on Firefox yet however as it needs some more changes. Mainly use `chrome.runtime` [here](https://github.com/emberjs/ember-inspector/blob/1c34df9e8e7f521b380d09d6f7d3af15c650cc78/app/adapters/chrome.js#L30)  and [here](https://github.com/emberjs/ember-inspector/blob/1c34df9e8e7f521b380d09d6f7d3af15c650cc78/app/adapters/chrome.js#L117). [`inspectedWindow.onResourceAdded`](https://github.com/emberjs/ember-inspector/blob/1c34df9e8e7f521b380d09d6f7d3af15c650cc78/app/adapters/chrome.js#L55) also doesn't seem to be supported in FF.

If we find there are still some minor differences between FF and Chrome (such as the `onResourceAdded` listener), we may need to keep the FF and Chrome adapters separate (but extend each other). Of course that'll mean we'll need to have one different dist for each browser but [share the same skeleton](https://github.com/emberjs/ember-inspector/blob/master/ember-cli-build.js#L190-L213). Thoughts?

Let me know if you need anything else, or if you're busy at the moment and you'd prefer that I take over the PR. Cheers!

**Comment by clarkbw** [comment]
@teddyzeenny please do take this over. I don’t think I’ll have as much time in the next couple of weeks. Thanks!

**Comment by teddyzeenny** [comment]
Superseded by https://github.com/emberjs/ember-inspector/pull/715

**Pull request closed without merging**
