### PR TITLE
glimmer-tree: Add controller null checks

### LINKED ISSUE #598: Components View Tree broken in ember 2.9.0-beta2
The current master (44e820f) as well as 2.0.2 break when the Component checkbox is ticked on the View Tree tab with the following exception:

**TypeError: Cannot read property 'get' of undefined**

Full Backtrace:

```
TypeError: Cannot read property 'get' of undefined
    at _default.controllerForComponent (<anonymous>:1821:35)
    at <anonymous>:1464:42
    at Array.forEach (native)
    at _default.componentsForController (<anonymous>:1463:20)
    at <anonymous>:1427:34
    at Array.map (native)
    at _default.build (<anonymous>:1342:63)
    at Class.viewTree (<anonymous>:4658:33)
    at <anonymous>:4630:27
    at fn (http://localhost:4200/assets/vendor.js:15457:18)
```

### PR DESCRIPTION
**Pull request by Turbo87**
... for components that don't have a parent controller

Resolves #598

### CODE REVIEW

**Comment by teddyzeenny** [comment]
Thanks!

**Comment by Turbo87** [comment]
@teddyzeenny can we get a bugfix release including this PR?

**Comment by teddyzeenny** [comment]
@Turbo87 sure thing. I'm leaving for emberfest - I will try do it there 😄

**Comment by teddyzeenny** [comment]
@Turbo87 2.0.4 is out!

**Comment by Turbo87** [comment]
awesome, thanks!

**Pull request merged**
