### PR TITLE
Avoid errors for router.router.recognizer.names as Object.create(null)

### LINKED ISSUE #634: Error message: routeNames.hasOwnProperty is not a function
```
ember.debug.js:5987 DEBUG: -------------------------------
ember.debug.js:5987 DEBUG: Ember      : 2.12.0-beta.2
ember.debug.js:5987 DEBUG: Ember Data : 2.12.0-beta.4
ember.debug.js:5987 DEBUG: jQuery     : 3.1.1
ember.debug.js:5987 DEBUG: -------------------------------
VM184:83 Ember Inspector Active
VM184:96 Ember Inspector has errored.
This is likely a bug in the inspector itself.
You can report bugs at https://github.com/emberjs/ember-inspector.
Error message: routeNames.hasOwnProperty is not a function
Stack trace: TypeError: routeNames.hasOwnProperty is not a function
    at Class.<anonymous> (<anonymous>:4050:25)
    at ComputedPropertyPrototype.get (http://localhost:4200/assets/vendor.js:27913:28)
    at Object.get (http://localhost:4200/assets/vendor.js:32894:19)
    at Class.get (http://localhost:4200/assets/vendor.js:45602:26)
    at Class.sendTree (<anonymous>:4060:28)
    at Class.getTree (<anonymous>:4030:14)
    at Object.sendEvent (http://localhost:4200/assets/vendor.js:28784:18)
    at Class.trigger (http://localhost:4200/assets/vendor.js:44894:19)
    at <anonymous>:3603:16
    at Class.<anonymous> (<anonymous>:3633:18)
warn @ VM184:96
handleError @ VM184:153
(anonymous) @ VM184:3635
run @ ember.debug.js:718
run @ ember.debug.js:22663
wrap @ VM184:3631
messageReceived @ VM184:3602
(anonymous) @ VM184:3594
(anonymous) @ VM184:131
_messageReceived @ VM184:130
(anonymous) @ VM184:324
run @ ember.debug.js:718
run @ ember.debug.js:22663
(anonymous) @ VM184:323
```

### PR DESCRIPTION
**Pull request by rwjblue**
Fixes #634

### CODE REVIEW

**Comment by rwjblue** [comment]
Haven't had a chance to dig into test failures, but they seem unrelated to this change (I suspect they are failing on master also).

**Comment by rwjblue** [comment]
@teddyzeenny - Any way you can release an version with the fix?

**Comment by mjsommer** [comment]
Ditto on that ... Not able to read routes in inspector.

**Comment by teddyzeenny** [comment]
@mjsommer which browser are you using?

**Comment by mjsommer** [comment]
I tried it in both Chrome and Firefox on Ubuntu 14.

**Comment by teddyzeenny** [comment]
@mjsommer which Ember and Ember Inspector versions do you see in your Info tab? I'm asking because a new version containing the fix was published yesterday to Chrome. Also is the error exactly `routeNames.hasOwnProperty is not a function`?

**Comment by sly7-7** [comment]
@teddyzeenny @mjsommer I think I've seen this error this morning, and disappear this afternoon. The info tab is now correctly pointing to 2.0.5

**Comment by mjsommer** [comment]
@teddyzeenny , here is my Info:

Ember Inspector	2.0.5
Ember	2.10.0-beta.2-patched-beta+dafad266
Ember Data	2.12.0-canary.c2af5be
jQuery	2.1.4

**Comment by mjsommer** [comment]
@teddyzeenny , error message:

Error message: Cannot read property 'dependencies' of undefined
Stack trace: TypeError: Cannot read property 'dependencies' of undefined
    at e.default.n.default.Service.extend.loadBundle

**Comment by mjsommer** [comment]
@teddyzeenny , error appears when clicking the Routes item. No routes are displayed, and the console throws the above error.

**Comment by teddyzeenny** [comment]
@mjsommer that looks like a different error (which needs a separate issue). Can you also include in the new issue a reproduction of the error in an online app/repo/JSBin? I don't think (not sure) there's any code that accesses the `dependencies` property in the inspector. There is the possibility that the error is caused by one of your route modules (because the Routes tab executes all route modules). Best way to debug this is to be able to reproduce the error somewhere.

**Comment by mjsommer** [comment]
@teddyzeenny Thanks Teddy. In learning about Ember, I have been reviewing various public Ember sites, like Heroku and LinkedIn. If you check them out in the Ember Inspector, you will notice that Routes works perfectly at https://dashboard.heroku.com/apps, but not at all with https://www.linkedin.com/feed/.

Perhaps it is LinkedIn's code, but since I do not work there, I am unable to fix it. It would be nice, though, if Ember Inspector was robust enough to be able to look past it.

PS: If anyone at LinkedIn wants to hire me to fix it, I am open! :)

**Pull request merged**
