### PR TITLE
Use brace expansion lint rule

### PR DESCRIPTION
**Pull request by ansmonjol**
Seems that eslint-plugin-ember support that now.

Test and linter are passing so I guess we're good with enabling this rule back.

### CODE REVIEW

**Comment by ansmonjol** [comment]
@rwwagner90 do you have an idea about the failing builds ? 🤔

**Comment by rwwagner90** [comment]
@ansmonjol try rebasing with master

**Comment by rwwagner90** [comment]
@ansmonjol I don't think removing the comma to trigger the build is going to do it. Can you please rebase with master?

**Comment by ansmonjol** [comment]
@rwwagner90 I was up to date with master 😕 
The failing job was pointing out a branch hash it cannot find. 
As I made a force push just before this failing test I hoped "just" retry CI jobs would work

**Comment by ansmonjol** [comment]
Have different fail now.
Had the same issue in another project today, it was due to a `moment` sub-package version in yarn that was failing. Let me see if I can find it back.

See https://github.com/moment/moment/pull/5025

**Pull request merged**
