### PR TITLE
Fix canary test failure

### PR DESCRIPTION
**Pull request by chancancode**
See https://github.com/emberjs/ember.js/issues/18673

### CODE REVIEW

**Comment by rwwagner90** [comment]
@chancancode it seems like there is another canary failure

**Comment by chancancode** [comment]
I’ll investigate 🧐

**Comment by rwwagner90** [comment]
@chancancode are we able to specify allowed failures with github actions? I think we allowed canary to fail before.

**Comment by rwwagner90** [comment]
I made the canary tests not required, so we can merge this in.

**Pull request merged**
