### PR TITLE
Stop deprecation logging in console

### PR DESCRIPTION
**Pull request by maheshsenni**

### CODE REVIEW

**Comment by teddyzeenny** [comment]
Thanks! Can you add a test [to this file](https://github.com/emberjs/ember-inspector/blob/a344132d71f0d2ee23a813667a477e3e5538c2f6/tests/ember_debug/deprecation_debug_test.js)? Something like the (untested) code below:
```js
//  Untested code
test("Warns once about deprecations", async function t(assert) {
  expect(2);
  let count = 0;
  port.get('adapter').reopen({
    debug(message) {
      assert.equal(message, 'Deprecations were detected, see the Ember Inspector deprecations tab for more details.');
      assert.equal(++count, 1, "Warns once");
    }
  });
  App.ApplicationRoute = Ember.Route.extend({
    setupController() {
      Ember.deprecate('Deprecation 1');
      Ember.deprecate('Deprecation 2');
    }
  });
  await visit('/');
});
```

**Comment by maheshsenni** [comment]
@teddyzeenny test added. Thanks for being patient :smile:

**Comment by teddyzeenny** [comment]
Looks good. Can you squash your commits?

**Comment by maheshsenni** [comment]
Squashed them into a single commit :+1:

**Comment by teddyzeenny** [comment]
Thanks!

**Pull request merged**
